apiVersion: batch/v1
kind: Job
metadata:
  name: abadia-ng-pretraining
  labels:
    name: abadia-ng-pretraining
spec:
  template:
    metadata:
        labels:
            name: abadia-ng-pretraining
    spec:
      containers:
      - name: agent
        image: gcr.io/abadia-1/abadia-agent-ng:v6
        command: ["/bin/bash", "-c"]
        args:
          - |
            gcloud components update --quiet
            tools/loop_pretraining.sh
            exit 0
        resources:
              requests:
                memory: "50Mi"
                cpu: "300m"
              limits:
                memory: "1024Mi"
                cpu: "940m"
      restartPolicy: OnFailure
  backoffLimit: 4
